/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: "#111111",
        canvas: "#ffffff",
        "on-primary": "#ffffff",
        "soft-cloud": "#f5f5f5",
        hairline: "#cacacb",
        "hairline-soft": "#e5e5e5",
        charcoal: "#39393b",
        ash: "#4b4b4d",
        mute: "#707072",
        stone: "#9e9ea0",
        sale: "#d30005",
        "sale-deep": "#780700",
        success: "#007d48",
        "success-bright": "#1eaa52",
        info: "#1151ff",
        "info-deep": "#0034e3",
        "accent-pink": "#ed1aa0",
        "accent-pink-soft": "#ffb0dd",
        "accent-purple-soft": "#beaffd",
        "accent-purple-pale": "#d6d1ff",
        "accent-teal": "#0a7281",
        "accent-pink-deep": "#4c012d",
      },
      fontFamily: {
        display: ["'Bebas Neue'", "'Futura ND'", "'Helvetica Neue'", "sans-serif"],
        sans: ["'Inter'", "'Helvetica Now Text'", "'Helvetica'", "'Arial'", "sans-serif"],
      },
      fontSize: {
        "display-campaign": ["96px", { lineHeight: "0.9", letterSpacing: "0" }],
        "heading-xl": ["32px", { lineHeight: "1.2", letterSpacing: "0" }],
        "heading-lg": ["24px", { lineHeight: "1.2", letterSpacing: "0" }],
        "heading-md": ["16px", { lineHeight: "1.75", letterSpacing: "0" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0" }],
        "body-strong": ["16px", { lineHeight: "1.5", letterSpacing: "0" }],
        "button-lg": ["24px", { lineHeight: "1.2", letterSpacing: "0" }],
        "button-md": ["16px", { lineHeight: "1.5", letterSpacing: "0" }],
        "button-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0" }],
        "link-md": ["16px", { lineHeight: "1.75", letterSpacing: "0" }],
        "caption-md": ["14px", { lineHeight: "1.5", letterSpacing: "0" }],
        "caption-sm": ["12px", { lineHeight: "1.5", letterSpacing: "0" }],
        "utility-xs": ["9px", { lineHeight: "1.75", letterSpacing: "0" }],
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "18px",
        xl: "24px",
        xxl: "30px",
        section: "48px",
      },
      borderRadius: {
        none: "0px",
        sm: "18px",
        md: "24px",
        lg: "30px",
        full: "9999px",
      },
      boxShadow: {
        "inset-hairline": "inset 0 -1px 0 #e5e5e5",
      },
    },
  },
  plugins: [],
}
